name: Integration Tests
on:
  workflow_dispatch: # on demand:
  push:
      branches: [metadata-from-pypi]


jobs:
  tests:
    name: 'Integration tests'
    strategy:
      matrix:
        python_version: [ '3.10', '3.11', '3.12', '3.13' ]
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          
      - name: Install dependencies
        run: |
          pipx install poetry
          poetry install --no-interaction

      - name: Run tests
        run: |
          poetry run pytest -vv --integration

