name: Integration Tests
on:
  workflow_dispatch: # on demand:


jobs:
  tests:
    name: 'Integration tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pipx install poetry
          poetry install --no-interaction

      - name: Run tests
        run: |
          poetry run pytest -vv --integration

